REATE DATABASE NexusWorldCup26
GO

-- RF-03: Gestión de Roles
CREATE TABLE [NexusWorldCup26].[dbo].[TABLA_ROLES](
	ID INT IDENTITY(1,1)  PRIMARY KEY,
	NOMBRE_ROL NVARCHAR(50) NOT NULL UNIQUE,
	DESCRIPCION NVARCHAR(100),
    FECHA_CREACION DATETIME DEFAULT GETDATE(),
    -- Definimos la columna y luego la restricción de valores
    ESTADO NVARCHAR(3) NOT NULL 
        CONSTRAINT CK_ROLES_ESTADO CHECK (ESTADO IN ('ACT', 'INA')) 
        CONSTRAINT DF_ROLES_ESTADO DEFAULT 'ACT',
    USUARIO_CREACION NVARCHAR(15) NOT NULL;
);

INSERT INTO TABLA_ROLES(NOMBRE_ROL) VALUES ('usuario'),('admin');

-- RF-01 y RF-02: Registro e Inicio de Sesión
CREATE TABLE [NexusWorldCup26].[dbo].[TABLA_USUARIOS](
	ID INT IDENTITY(1,1)  PRIMARY KEY,
	NOMBRE NVARCHAR(100) NOT NULL,
	EMIAL NVARCHAR(150) NOT NULL UNIQUE,
	PASSWORD_HASH NVARCHAR(200) NOT NULL,
	ROL INT NOT NULL DEFAULT 1,
	FECHA_CREACION DATETIME DEFAULT GETDATE(),

	CONSTRAINT FK_USUARIO_ROLES
	FOREIGN KEY (ROL) REFERENCES TABLA_ROLES(ID)

	);
	
	-- RF-04: Registro de Equipos
CREATE TABLE TBL_EQUIPOS (
    EquipoID INT PRIMARY KEY IDENTITY(1,1),
    NombreEquipo VARCHAR(100) NOT NULL,
    EscudoURL VARCHAR(255),
    Grupo CHAR(1), -- Ejemplo: 'A', 'B' para RF-07
	Estado NVARCHAR(3) NOT NULL 
        CHECK (ESTADO IN ('ACT', 'INA')) 
        DEFAULT 'ACT'
);

-- RF-05 y RF-06: Registro de Partidos y Resultados
CREATE TABLE TBL_PARTIDOS (
    PartidoID INT PRIMARY KEY IDENTITY(1,1),
    EquipoLocalID INT FOREIGN KEY REFERENCES TBL_EQUIPOS(EquipoID),
    EquipoVisitanteID INT FOREIGN KEY REFERENCES TBL_EQUIPOS(EquipoID),
    FechaPartido DATETIME NOT NULL,
    Estadio VARCHAR(100),
    Fase VARCHAR(50), -- 'Grupos', 'Cuartos', 'Final'
    GolesLocal INT DEFAULT NULL,
    GolesVisitante INT DEFAULT NULL,
    Estado_Juego VARCHAR(20) DEFAULT 'PROGRAMADO' -- 'PROGRAMADO', 'FINALIZADO'
);